version: '3'
services:
  backend:
    image: luis2200/express:latest
    container_name: express
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - redis
      - mongo
      - angular
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  mongo:    
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  angular:    
    image: luis2200/angular:latest
    container_name: angular
    ports:
      - "8000:4200"